# Default values for inventory-db-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres:13.1-alpine
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

configMap:
  labels:
    app: postgres-app
  data:
    POSTGRES_DB: inventory_pg
    POSTGRES_USER: postgresadmin

secret:
  type: Opaque
  labels:
    app: postgres-app
  data:
    POSTGRES_PASSWORD: Z3JvdXA2LWZ0dwo=

statefulSet:
  labels:
    app: postgres-app
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    labels:
      app: postgres-app
  containers:
    - name: postgres-container
      image: postgres:13.1-alpine
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  envFrom:
    - configMapRef: 
        name: postgres-config
    - secretRef:
        name: postgres-secret
  volumeClaims:
    - metadata:
        name: postgresdb
      accessModes: ['ReadWriteOnce']
      storageSize: 5Gi

service:
  type: ClusterIP
  labels:
    app: postgres-app
  ports: 
    - port: 5432
  selector: 
    app: postgres-app

policies:
  labels:
      app: postgres-app
  podSelector:
      app: postgress-app
  ingress:
    enabled: true
    from:
      podSelector:
        app: inventory-api
      ports:
        - protocol: TCP
          port: 5432
  egress:
    enabled: true
    to: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
