apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-ingress-policy
  {{- with .Values.policies.ingress }}
  labels:
    {{- range $key,$value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- range $key,$value := .podSelector}}
      {{ $key }}: {{ $value }}
      {{- end }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- range $key,$value := .from.podSelector }}
          {{ $key }}: {{ $value }}
          {{- end }}
  {{- end }}