apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
  {{- with .Values.configMap }}
  labels:
    {{- range $key,$value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  {{- range $key,$value := .data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}