apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  {{- with .Values.secret }}
  labels:
    {{- range $key,$value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: {{ .type }}
data:
  {{- range $key,$value := .data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}