apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-clusterip
  {{- with .Values.service }}
  labels:
    {{- range $key,$value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec: 
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - port: {{ .port }} # This also sets 'targetPort' to {{ .port }}
    {{- end }}
  selector:
    {{- range $key,$value := .selector }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}