{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{- with .Values.rbac.roleBinding }}
metadata:
  name: {{ $.Release.Name }}-{{ .namespace }}-get-list-services-role-binding
  namespace: {{ .namespace }}
subjects:
  {{- range .subjects }}
  - kind: {{ .kind }}
    name: {{ $.Release.Name }}-{{ .name }}
    apiGroup: {{ .apiGroup }}
  {{- end }}
roleRef:
  {{- range $key,$value := .roleRef }}
  {{- if eq $key "name" }}
  {{ $key }}: {{ $.Release.Name }}-{{ $value }}
  {{- else }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}