{{- if .Values.tlsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecret.name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecret.crt }}
  tls.key: {{ .Values.tlsSecret.key }}
{{- end }}