apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-ui-deployment
  labels:
    app: inventory-ui
spec:
  selector:
    matchLabels:
      app: inventory-ui
  template:
    metadata:
      labels:
        app: inventory-ui
    spec:
      containers:
        - name: inventory-ui-container
          image: docker.io/macsi21/inventory-ui:v1
          ports:
            - containerPort: 80
      restartPolicy: Always
