apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui-deployment
  {{- with .Values.deployment }}
  labels:
    {{- range $key,$value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- range $key,$value := .selector.matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key,$value := .template.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
        {{- $imageVersion := .imageVersion }}
        {{- range .containers }}
        - name: {{ .name }}
          image: {{ .image }}:{{ $imageVersion }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
        {{- end }}
      {{- if $.Values.rbac.serviceAccount.create }}
      {{- range .serviceAccounts }}
      serviceAccount: {{ $.Release.Name }}-{{ .name }}
      serviceAccountName: {{ $.Release.Name }}-{{ .name }}
      {{- end }}
      {{- end }}
  {{- end }}
