{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
  {{- with .Values.autoscaling }}
    kind: {{ .kind }}
    name: {{ $.Release.Name }}-ui-deployment
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  {{- range $key,$value := .metric }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
{{- end }}