apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-ui-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65